#+title: Nico’s SICP notes

These are the notes for the second edition, which is authored by by
Harold Abelson and Gerald Jay Sussman, with Julie Sussman


* Personal Glossary

- <<environment>> :

- <<prefix notation>> ::

  - Putting the operator to the left of the operands.  Contrast it to
    ‘infix notation’, for example, in addition:

    - prefix notation: ~+ 1 2 3 4 5~
    - infix notation: ~1 + 2 + 3 + 4 + 5~

    See also some [[prefix-notation-advantages][advantages of using prefix notation for procedure
    application]]

- <<primitive>> ::

- <<expression>> ::

  - Something that can be ‘evaluated’, ie, resolves to a value.

  - There are [[primitive expressions]], example, a number (evaluates to
    the number value), and there are [[compound expressions]], for
    example, a procedure application over its arguments (which is a
    combination made of sub expressions).

- <<programming language>> ::

  - [[programing-language-process-idea-framework][Framework for organizing ideas about processes.]]

- <<idiom>> <<idioms>> ::

  - plural: small, standard correct structures used in composing
    greater progams.  See the [[foreword-idiom-definition-quote]]

- <<algorithm>> ::

  - A program that perform a precise mathematical function, where is
    desired that they behave optimally, specially regarding execution
    time and storage.  See the [[foreword-algorithm-definition-quote]]

- <<procedural epistemology>> ::

  - Study of the structure of knowledge in an imperative point of
    view.  It answers ‘how to’ instead of ‘what is’.  See
    [[preface-1e-procedural-epistemology-quote]]

- <<process>> ::

  - For a lax description, see [[Process, data, and program]]

- <<data>> ::

  - For a lax description, see [[Process, data, and program]]

- <<program>> ::

  - For a lax description, see [[Process, data, and program]]

- <<interpreter>> ::

- <<LISP>> ::

  - LISt Processing

- <<special form>> ::

  - A form that doesn’t evaluate according to the rules of the
    [[general evaluation rule]]


* Notes

** Foreword
[[info:sicp#Foreword]]
Foreword written by Alan J Perlis.

- The subject matter sets three foci of consideration:

  - The mind:  Every program is a model that starts in the mind.

  - Collection of computer programs: a knowledge of correct idioms and
    proven techniques for combining them.

  - The computer: The computer obeys the laws of physics, another model.

- Idioms definition quote:

  <<foreword-idiom-definition-quote>>
  #+begin_quote
  (...) complete formal arguments of correctness seldom accompany large
  programs.  Since large programs grow from small ones, it is crucial
  that we develop an arsenal of standard program structures of whose
  correctness we have become sure--we call them idioms--and learn to
  combine them into larger structures using organizational techniques of
  proven value.
  #+end_quote

- Algorithm definition quote:

  <<foreword-algorithm-definition-quote>>
  #+begin_quote
  Among the programs we write, some (but never enough) perform a
  precise mathematical function such as sorting or finding the maximum
  of a sequence of numbers, determining primality, or finding the
  square root.  We call such programs algorithms, and a great deal is
  known of their optimal behavior, particularly with respect to the
  two important parameters of execution time and data storage
  requirements.
  #+end_quote

- Advice

  #+begin_quote
  A programmer should acquire good algorithms and idioms.
  #+end_quote


** Preface 1e
[[info:sicp#Preface 1e]]

- Computer programs can be a formal medium for expressing
  methodological ideas:

  #+begin_quote
  (...) a computer language is not just a way of getting a computer to
  perform operations but rather that it is a novel formal medium for
  expressing ideas about methodology.
  #+end_quote

- Procedural epistemology quote

  <<preface-1e-procedural-epistemology-quote>>
  #+begin_quote
  (...) "procedural epistemology" -- the study of the structure of
  knowledge from an imperative point of view, as opposed to the more
  declarative point of view taken by classical mathematical subjects.
  Mathematics provides a framework for dealing precisely with notions
  of "what is."  Computation provides a framework for dealing
  precisely with notions of "how to."
  #+end_quote


** Building Abstractions With Procedures
[[info:sicp#Chapter 1]]

This chapter delves into the idea of a "computational process".

- <<Process, data, and program>> :
  - process :: beings that inhabits a computer
  - data :: abstract things manipulated by processes
  - program :: pattern of rules that directs a process

  So we could say, a process, the thing living in the computer,
  manipulates data directed by the program.

- On good engineering:

  - Organize programs in such a way that:

    - We can be reasonable sure they will perform the intended tasks.
    - Unanticipated problems don’t lead to catastrophe.
    - Problems can be debugged.
    - Are modular: new parts can be made or replaced indepently.

  - Visualize process behaviour in advance


*** The Elements of Programming
[[info:sicp#1-1]]

- On programming languages:

  - They can be understood as a framework for organizing ideas about
    processes.  <<programing-language-process-idea-framework>>

    Thus when thinking about a language we should ask ourselves, what
    are the means the language provides for combining simple ideas
    into complex ideas?

  - In regards to organizing ideas about processes, powerful
    languages provides the following mechanisms:

    - Primitive expressions: Simplest entities the language is
      concerned with.

    - Means of combination: Used to make compound elements.

    - Means of abstraction: by which compound elements can be *named*
      and manipulated as units.


**** Expressions
[[info:sicp#1-1-1]]

- [[expression]] (in glossary)

- An expression is an statement/description that can be evaluated, ie,
  reduced to a single value.

- There are <<primitive expressions>> :

  - Eg, those representing numbers: for integers, the numbers typed as
    themselves, evaluate to those numbers:

    #+begin_src scheme
      27
    #+end_src

    #+RESULTS:
    : 27

  - Or e.g., those representing procedures, such as the add procedure
    ‘+’ which is a primitive procedure.

    #+begin_src scheme
      +
    #+end_src

    #+RESULTS:
    : #<procedure + (#:optional _ _ . _)>

- And there are <<compound expressions>> :

  - Representing procedure application.  For example, add
    ‘+’ can be combined with number expressions to represent the
    adding application, ie, sum:

    #+begin_src scheme
      (+ 1 2 3 4 5)
    #+end_src

    #+RESULTS:
    : 15

  - This type of compound expression representing procedure
    application will be called a /combination/.  In a combination, the
    first element is the operator and the rest are the operands.

    Putting the operator first and the arguments later is called
    [[prefix notation]].

    :personal-note:
    I guess its called combination as in, combination of expressions.
    The combination in itself its also an expression, because it
    evaluates, it produces a value.  Simple ideas get combined to
    represent a complex idea.  The framework for thinking about
    processes: define simple ideas, define a way to combine them,
    create complex ideas through the combinations.
    :end:

  - Prefix notation has the following advantages in regarding to
    procedure application: <<prefix-notation-advantages>>

    - Being able to accomodate an arbitrary number of arguments.

      - infix sum, always takes two args: ~1 + 2~, that is,
        ~left + right~

      - prefix sum can take any: ~+ 1 2 3 4 5 ... n~

      This applies for any operation.

    - Easier evaluation model, due to uniformity

      #+begin_quote
      A second advantage of prefix notation is that it extends in a
      straightforward way to allow combinations to be nested, that is,
      to have combinations whose elements are themselves combinations
      #+end_quote

      In programming languages with infix notation, we require to know
      the arity of each operation, and we need parenthesis to override
      the natural order of each operation.  For example:

      #+begin_src python
        return 1 + 2 * 3 - 1 / 2
      #+end_src

      #+RESULTS:
      : 6.5

      To evaluate this we would nee to follow the general rules of
      math, that is, first multiply and divide in the order of
      appareance, then add and substract in order of appearance.  This
      gets more complicated with larger expressions, with each
      operator having it’s own precedence rules.

      In lisp, due to the delimited procedures, the use of prefix
      notation creates a simple and straightforward evaluation model,
      that is uniform and unambiguos:

      #+begin_src scheme
        (- (+ 1
              (* 2 3))
           (/ 1 2))
      #+end_src

      #+RESULTS:
      : 13/2

      We don’t need to know arity, we just follow recursively the same
      evaluation rules, i.e., first element is procedure, rest are
      arguments.  We can evaluate each sub expression at a time
      without problems.

- The interpreter works by evaluating expressions one at a time, and
  printing their results.  That is why it’s said that it works in a
  ‘read-eval-print’ loop, also know as ‘repl’


**** Naming and the Environment
[[info:sicp#1-1-2]]

- Languages allow to /refer/ to computational objects *by name*.

- A name identifies a "variable" whose "value" *is* the computational
  object:

  : name -> variable -> value

  By the name we identify and refer to the variable, which holds the
  computational object.

  :personal-note:
  It’s worth noting that just as in real life, the word is not the thing
  (the word "dog" is not the dog), it’s just used to refer to it.
  Thats why the name can also be called a symbol; as in, symbols
  refers to things, as in, the symbol "dog" refers to a dog.
  :end:

- We should ask ourselves, what means do any specific language
  provides for naming computational objects.

  In scheme we use ‘define’:

  #+begin_src scheme
    ; use ‘define’ for naming the object ‘2’ with the name ‘size’
    (define size 2)
    ; use the name ‘size’ to reffer to the object ‘2’
    size ;; => 2
  #+end_src

  #+RESULTS:
  : 2

  From now on we can refer to this object (number two) by the name
  ‘size’.

- Naming is one of our means of /abstraction/.  We don’t need to
  replicate all the details of complex computational objects each time
  we want to use them; we just refer to them by name.

- The ability to associate a symbol with a value, and later retrieve
  that value by the symbol name, means that the interpreter must keep
  track of those name-value associations in some kind of memory.  This
  "memory" is called an [[environment]], and there can be many environments.


**** Evaluating Combinations
[[info:sicp#1-1-3][sicp#1-1-3]]

Chapter goal: Thinking procedurally, dealing with issues related to
it.

Case: /The interpreter/.  In order to evaluate combinations *it
follows a procedure*: <<general evaluation rule>>

#+begin_quote
To evaluate a combination, do the following:

  1. Evaluate the subexpressions of the combination.

  2. Apply the procedure that is the value of the leftmost
     subexpression (the operator) to the arguments that are the
     values of the other subexpressions (the operands).
#+end_quote

From this procedure description we can note important things about
processes in general:

- In order to evaluate a combination, first we need to evaluate each
  element of the combination.  Thus the rule is said to be
  *recursive*; it’s defined in terms of itself.

  A recursive definition can succintly handle complex cases.  The
  simple rule describes perfectly the steps for evaluating any deep
  nested combination such as this:

  #+begin_src scheme
   (* (+ 2 (* 4 6))
      (+ 3 5 7))
  #+end_src

  Recursion is *very* powerful for dealing with tree-like objects.

- The type of process of the previous example can be represented by a
  tree, where each combination is a node with branches for the
  operator and it’s operands:

  #+begin_example
      390
      /|\____________
     / |             \
    ,*  26            15
       /|\            |
      / | \         // \\
     +  2  24      / |  | \
           /|\    +  3  5  7
          / | \
         ,*  4  6
  #+end_example

  From this representation we can note that:

  - Terminal nodes (nodes without branches) are either operators or
    primitives.

  - We can /see/ how the values "percolate" upwards, from terminal nodes
    to higher levels.  This type of process is called "tree
    accumulation".  The evaluation rule is an example of tree
    accumulation.

- The repeated application of the first step will inevitable lead us
  to the point of evaluating non-combinations, such as primitives or
  names.  These are evaluated as follows:

  - Number literals represent themselves

  - Operations are machine operations (for example add)

  - Names’s values are taken from the associated objects in the
    environment.  Thus the environment determines the meaning of
    symbols.

- This general rule doesnt hold for everything.

  For Example: ~(define x 3)~ doesnt apply ~define~ to both ~x~ and ~3~. ~x~ has
  no value prior of ~define~; ~x~ is meaningful only after ~define~

  All of these exceptions are called *special forms* <<special form>> :

  - Each one has it’s own rules / order of evaluation.

- The set of all types of expressions with their evaluation rules
  constitute the *syntax* of the language

  - Lisp is simpler here, because:
    - One general evaluation rule
    - Small set of special forms with their own rules


**** Compound Procedures
[[info:sicp#1-1-4][sicp#1-1-4]]

Powerful programming languages also provide the means of abstracting
compound operations and referring to them as a unit.  This will be
called <<procedure definition>> .

In scheme we also use ‘define’ for this:

#+begin_src scheme
 ;; defines the ‘square’ procedure, which squares a number ‘x’
 (define (square x) (* x x))
#+end_src

, which for this language could be read as (in plain english):

#+begin_example
 (define (square    x)         (*      x         x))
   |        |       |           |      |         |
  To     square  something,  multiply  it  by  itself.
#+end_example

Notable things:

- Two things happen during ~define~: the creation of the compound
  procedure ~(* x x)~, and the naming of it as ~square~.  Even though
  these two are together right now, they don’t need to be together: a
  procedure can exist without a name, and a name can be unbound to any
  object.

- Once a procedure is defined, it can be used by its name, just like
  any other procedure, builtin or not.

  One useful example: using it as a building block for other
  procedures:

  #+begin_src scheme
    (define (sum-of-squares x y)
      (+ (square x) (square y)))
    ;; later on, when calling this:
    (sum-of-squares 3 4)
    ;; the repl prints: 25
  #+end_src

  The means of abstraction allows for more straightforward use in
  ~sum-of-squares~.

Worth noting about lisp:  The ~define~ form allows us to use a sequence
of expressions as its body.  The procedure’s return value becomes the
value of the last expression evaluated.


**** The Substitution Model for Procedure Application
[[info:sicp#1-1-5][sicp#1-1-5]]

We have answered how evaluation happens for compound procedures: we
follow the same rule described in [[*Evaluating Combinations]], which
shortly is:

1. Evaluate all elements.

2. *Apply* the procedure (the first element) to the arguments (the rest
   of elements)

How does compound procedure application works?  We can use the
following model:

#+begin_quote
 To apply a compound procedure to arguments, evaluate the body of
 the procedure with each formal parameter replaced by the
 corresponding argument.
#+end_quote

Given this model, how would application of ~(f 5)~ go?

#+begin_src scheme
  (define (square x)
    (* x x))

  (define (sum-of-squares x y)
    (+ (square x) (square y)))

  (define (f a)
    (sum-of-squares (+ a 1) (* a 2)))

  (f 5) ; ?
#+end_src

1. we start by evaluating ~f~ and ~5~:

   : f ;; => (sum-of-squares (+ a 1) (* a 2))

   : 5 ;; => 5

2. we replace the formal parameter ~a~ by ~5~:

   : (sum-of-squares (+ 5 1) (* 5 2))

3. we reapply the same evaluation rules, now to the ~sum-of-squares~
   combination.  We evaluate the elements:

   : sum-of-squares ;; => (+ (square x) (square y))

   : (+ 5 1) ;; => 6

   : (* 5 2) ;; => 10

4. In ~sum-of-squares~ we substitute formal parameters ~x~ by ~6~ and ~y~ by ~10~:

   : (+ (square 6) (square 10))

5. We evaluate the elements:

   : + ;; => primitive procedure

   : (square 6) ;; => (* 6 6) => 36

   : (square 10) ;; => (* 10 10) => 100

6. Finally we apply the primitive procedure:

   : (+ 36 100) ;; => 136


This way to think about compound procedure application is called the
<<substitution model>> , which could roughly be understood as ‘to
understand procedure application, you substitute the formal parameters
with the operands’.

Two things to stress about this model:

1. Its useful to think about procedure application, not to describe
   how the interpreter works.

   Normally interpreters don’t substitute the text of the procedure to
   replace formal parameters with their values; normally an
   ‘environment’ would be used to bind formal parameters.

2. The substitution is a simplified and incomplete model which is
   useful to introduce formal thinking of the evaluation process.
   We’ll see more elaborate models as we go on.


***** Applicative order versus normal order
[[info:sicp#1-1-5][sicp#1-1-5]]

The evaluation model we’ve seen so far worked by evaluating all
elements, and *then* applying the resulting procedure to the resulting
arguments.

An alternative evaluation model could evaluate their operands *only
when their values were needed*.  This method would:

1. Subtitue the formal parameter by the whole unevaluated operand
   expressions.

2. Evaluate when we obtain an expression with only primitive
   expressions.

Using this method, the evaluation of ~(f 5)~ becomes:

#+begin_example
     (sum-of-squares (+ 5 1) (* 5 2))                 ;; 1

     (+    (square (+ 5 1))      (square (* 5 2))  )  ;; 2.  We take the whole operands (+ 5 1) and put them into the body of square.

     (+    (* (+ 5 1) (+ 5 1))   (* (* 5 2) (* 5 2))) ;; 3.  Now we only have primitive expressions.

;; followed by the reductions

     (+         (* 6 6)             (* 10 10))        ;; 4

     (+           36                   100)           ;; 5

                         136                          ;; 6

#+end_example

Things worth noting:

- By substituting the unevaluated operands into the body of compound
  procedures, the subprocedures ~(+ 5 1)~ and ~(* 5 2)~ now get evaluated
  *twice* (3).

- This evaluation method is called <<normal order evaluation>> , which
  is contrasted by <<applicative order evaluation>> , the evaluation
  method normally used by the interpreter.

- Even though this example returned the same value for both evaluation
  methods, normal order won’t always produce the same results as
  applicative order.

- It could be said the lisp interpeter defaults to applicative order
  evaluation because:

  - This way it avoids unnecesary extra evaluation (For example, don’t
    evaluate ~(+ 5 1)~ twice)

  - Procedures that can’t be modeled by substitution become much
    more complicated using normal order.


**** Conditional Expressions and Predicates
[[info:sicp#1-1-6][sicp#1-1-6]]

In order to create more expressive procedures it becomes necessary to
be able to perform *tests*, and to *take differrent actions* based on the
result of those tests.

Example:  Calculating absolute value.

Ascii case analysis:

:       /
:       |   x  if x > 0
: |x| = <   0  if x = 0
:       |  -x  if x < 0
:       \

In lisp, one can use ~cond~ for case analysis.  Quoting the book:

#+begin_src scheme
  (define (abs x)
    (cond ((> x 0) x)
          ((= x 0) 0)
          ((< x 0) (- x))))
#+end_src

The general form of a conditional expression is:

#+begin_src scheme
  (cond (<P1> <E1>)
        (<P2> <E2>)
        ...
        (<PN> <EN>))
#+end_src

Where each P stands for <<predicate>> , an expression returning a true
or false value, i.e., a boolean.  Each E is any expression.

~cond~ evaluation work in the following way:

- Evaluate P1.  If P1 evaluates to false value, proceed with the
  following P.

- If any P returns a true value, then proceed to evaluate the
  corresponding E expression, wich formally is called the *consequent*
  expression.  The result of E is the result of the whole ~cond~ form.

- If neither P returns a true value, then ~cond~ has an undefined return
  value.

- Finally, is worth noting that the word ~else~ can be used in place of
  a predicate P.  In that case, its understood this is the last clause
  of the ~cond~ expression.  One could define absolute value as this:

  #+begin_src scheme
    (define (abs x)
      (cond ((< x 0) (- x))
            (else x)))
  #+end_src

In scheme, another special form one could use is ~if~, which is best
suited when there are only two cases in case analysis, which has the
following structure:

#+begin_src scheme
  (if <PREDICATE> <CONSEQUENT> <ALTERNATIVE>)
#+end_src

The evaluation works as follow:

1. Evaluate the <PREDICATE> expression.

2. If <PREDICATE> returned a true value, evaluate the <CONSEQUENT> expression.

3. If <PREDICATE> returned a false value, evaluate the <ALTERNATIVE> expression.

We’ve seen some primitve predicates (~<~, ~>~, ~=~).  Also as important are
some of the *logical composition operators* such as:

- ~and~:
- ~or~:
- ~not~:

  To be continued...

**** Example: Square Roots by Newton's Method

**** Procedures as Black-Box Abstractions

*** Procedures and the Processes They Generate

*** Linear Recursion and Iteration

**** Tree Recursion

**** Orders of Growth

**** Exponentiation

**** Greatest Common Divisors

**** Example: Testing for Primality

*** Formulating Abstractions with Higher-Order Procedures

**** Procedures as Arguments

**** Constructing Procedures Using `Lambda'

**** Procedures as General Methods

**** Procedures as Returned Values

** Building Abstractions with Data

*** Introduction to Data Abstraction

**** Example: Arithmetic Operations for Rational Numbers

**** Abstraction Barriers

**** What Is Meant by Data?

**** Extended Exercise: Interval Arithmetic

*** Hierarchical Data and the Closure Property

**** Representing Sequences

**** Hierarchical Structures

**** Sequences as Conventional Interfaces

**** Example: A Picture Language

*** Symbolic Data

**** Quotation

**** Example: Symbolic Differentiation

**** Example: Representing Sets

**** Example: Huffman Encoding Trees

*** Multiple Representations for Abstract Data

**** Representations for Complex Numbers

**** Tagged data

**** Data-Directed Programming and Additivity

*** Systems with Generic Operations

**** Generic Arithmetic Operations

**** Combining Data of Different Types

**** Example: Symbolic Algebra

** Modularity, Objects, and State

*** Assignment and Local State

**** Local State Variables

**** The Benefits of Introducing Assignment

**** The Costs of Introducing Assignment

*** The Environment Model of Evaluation

**** The Rules for Evaluation

**** Applying Simple Procedures

**** Frames as the Repository of Local State

**** Internal Definitions

*** Modeling with Mutable Data

**** Mutable List Structure

**** Representing Queues

**** Representing Tables

**** A Simulator for Digital Circuits

**** Propagation of Constraints

*** Concurrency: Time Is of the Essence

**** The Nature of Time in Concurrent Systems

**** Mechanisms for Controlling Concurrency

*** Streams

**** Streams Are Delayed Lists

**** Infinite Streams

**** Exploiting the Stream Paradigm

**** Streams and Delayed Evaluation

**** Modularity of Functional Programs and Modularity of Objects

** Metalinguistic Abstraction

*** The Metacircular Evaluator

**** The Core of the Evaluator

**** Representing Expressions

**** Evaluator Data Structures

**** Running the Evaluator as a Program

**** Data as Programs

**** Internal Definitions

**** Separating Syntactic Analysis from Execution

*** Variations on a Scheme -- Lazy Evaluation

**** Normal Order and Applicative Order

**** An Interpreter with Lazy Evaluation

**** Streams as Lazy Lists

*** Variations on a Scheme -- Nondeterministic Computing

**** Amb and Search

**** Examples of Nondeterministic Programs

**** Implementing the `Amb' Evaluator

*** Logic Programming

**** Deductive Information Retrieval

**** How the Query System Works

**** Is Logic Programming Mathematical Logic?

**** Implementing the Query System

*** Implementing the Query System

**** The Driver Loop and Instantiation

**** The Evaluator

**** Finding Assertions by Pattern Matching

**** Rules and Unification

**** Maintaining the Data Base

**** Stream Operations

**** Query Syntax Procedures

**** Frames and Bindings

** Computing with Register Machines

*** Designing Register Machines

**** A Language for Describing Register Machines

**** Abstraction in Machine Design

**** Subroutines

**** Using a Stack to Implement Recursion

**** Instruction Summary

*** A Register-Machine Simulator

**** The Machine Model

**** The Assembler

**** Generating Execution Procedures for Instructions

**** Monitoring Machine Performance

*** Storage Allocation and Garbage Collection

**** Memory as Vectors

**** Maintaining the Illusion of Infinite Memory

*** The Explicit-Control Evualtor

**** The Core of the Explicit-Control Evaluator

**** Sequence Evaluation and Tail Recursion

**** Conditionals, Assignments, and Definitions

**** Running the Evaluator

*** Compilation

**** Structure of the Compiler

**** Compiling Expressions

**** Compiling Combinations

**** Combining Instruction Sequences

**** An Example of Compiled Code

**** Lexical Addressing

**** Interfacing Compiled Code to the Evaluator
